version: "3"

services:
  mysql:
    image: mysql:latest
    volumes:
      - remember-me-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  remember-me-mysql:
