version: "3"

services:
  mysql:
    image: mysql:latest
    volumes:
      - remember-me-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:latest

  server:
    depends_on:
      - mysql
      - redis
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # volume 변경 사항이 container에 즉각 반영(윈도우 용)
    command: npm run dev

volumes:
  remember-me-mysql:
